module top_lab5 (
    input wire CLK100MHZ,       // Onboard 100 MHz clock source
    input wire [4:0] SW,        // SW[4:0] speed selection
    input wire BTN0,            // Reset button (Active-Low)
    input wire BTN1,            // Direction button (1 = Up, 0 = Down)
    output wire [1:0] AN,       // Anode signals for the physical displays
    output wire [6:0] SEG       // Shared segment lines (A to G)
);

    // ================= INTERNAL SIGNAL ROUTING =================
    wire clk_div;               // The slow clock generated by the clock divider
    wire [3:0] units_bcd;       // Units count line bridging counter to display
    wire [3:0] tens_bcd;        // Tens count line bridging counter to display

    // To generate the ~1.5 kHz scan clock, we need a wire that taps 
    // directly into the intermediate stages of the free-run counter. 
    // We will extract this tap point by passing a dummy wire to our clock divider.
    wire [31:0] raw_counter_bus;

    // ================= 1. THE SPEED CONTROL SYSTEM =================
    // This drives the counter and selects our divided slow clock (clk_div)
    clock_divider clk_system (
        .clk(CLK100MHZ),
        .rst_n(BTN0),
        .sel_speed(SW),
        .clk_divider(clk_div),
        .counter_bus(raw_counter_bus) // Taps the internal counter for the display scanning clock
    );

    // ================= 2. THE CASCADED COUNTER SYSTEM =================
    // Runs on our variable-speed slow clock (clk_div)
    bcd_up_down_counter bcd_counter_inst (
        .clk(clk_div),
        .dir(BTN1),
        .rst_n(BTN0),
        .enable(1'b1), // Always enabled to continuously run
        .output_units_reg(units_bcd),
        .output_tens_reg(tens_bcd)
    );

    // ================= 3. THE DISPLAY DRIVE SYSTEM =================
    // Uses raw_counter_bus[15] (~1.5 kHz) to rapidly cycle active digits
    seg7_scan display_driver (
        .clk_scan(raw_counter_bus[15]),
        .rst_n(BTN0),
        .units_bcd(units_bcd),
        .tens_bcd(tens_bcd),
        .AN(AN),
        .SEG(SEG)
    );

endmodule
